FROM python:3.8-slim

WORKDIR /usr/src/app

RUN apt-get update -y

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY  ./ /usr/src/app

RUN mkdir /root/Downloads

CMD [ "python",  "-m", "pytest", "tests/", "-v"]