apiVersion: apps/v1
kind: Deployment

# Describes the deployment
metadata:
  name: ItJobsWatch
  labels:
    app: ho-project
    tier: ItJobsWatch

spec:
  replicas: 3

  # Selects the template that has the label 'tier: ItJobsWatch'
  selector:
    matchLabels:
      tier: ItJobsWatch

  template:
    metadata:
      labels:
        tier: ItJobsWatch
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hostname
                operator: NotIn
                values:
                - ip-69-69-69-194
                
      # Here you can define a pod like before
      containers:
      - name: ho-project
        image: arunpanesar42/ho_project:latest
