apiVersion: apps/v1
kind: Deployment

# Describes the deployment
metadata:
  name: it-jobs-watch
  labels:
    app: ho-project
    tier: it-jobs-watch

spec:
  replicas: 3

  # Selects the template that has the label 'tier: it-jobs-watch'
  selector:
    matchLabels:
      tier: it-jobs-watch

  template:
    metadata:
      labels:
        tier: it-jobs-watch
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hostname
                operator: NotIn
                values:
                - ip-69-69-69-194
                
      # Here you can define a pod like before
      containers:
      - name: ho-project
        image: arunpanesar42/ho_project:latest
        imagePullPolicy: "Always"
      dnsPolicy: "None"
        dnsConfig:
          nameservers:
            - 1.1.1.1